easy_admin:
  entities:
    Post:
      label: 'Articles'
      class: App\Entity\Post
      controller: App\Controller\PostController
      form:
        fields:
          - { property: 'title', label: 'Titre', type: 'text' }
          - { property: 'content', label: 'Contenu', type: 'textarea' }

      list:
        title: "Articles"
        fields:
          - { property: 'id' }
          - { property: 'title', label: 'Titre'}
          - { property: 'slug', label: 'Slug'}
          - { property: 'created', label: 'Crée le'}
          - { property: 'updated', label: 'Mis à jour le'}
          - { property: 'deleted', label: 'Supprime le'}
