easy_admin:
  entities:
    Seance:
      label: 'Séances'
      class: App\Entity\Seance
      controller: App\Controller\SeanceController
      form:
        fields:
          - { property: 'totalSubscriptions', label: 'Inscriptions Total', type: 'integer' }
          - { property: 'maxSubscriptions', label: 'Maximum Inscriptions', type: 'integer' }

      list:
        title: "Séances"
        fields:
          - { property: 'id' }
          - { property: 'media', label: 'Film' }
          - { property: 'date' }
          - { property: 'totalSubscriptions', label: 'Titre' }
          - { property: 'maxSubscriptions', label: 'Titre' }
          - { property: 'created', label: 'Crée le' }
          - { property: 'updated', label: 'Mis à jour le' }
          - { property: 'deleted', label: 'Supprime le'}
